### ISSUE TITLE
Why? :)

### ISSUE THREAD

**Issue by feoh** [shapr/metalogo#1]
One of the things I'd love to see in the project README is: Why is it desirable to reduce the intentionally English-wordy LOGO syntax down to APL like symbols? What does this achieve?

I'm SURE there's a good answer because you're crazy smart and it may well be "BECAUSE I CAN NOW GO AWAY AND LET ME WRITE SOME MOAR HASKELL!" but I'd still love to see that :)

**Comment by shapr** [comment]
It's because I want to be able to hand draw logo on an e-ink tablet, and have the symbol recognizer execute that logo to then  draw more logo that can also be recognized.

**Comment by feoh** [comment]
I look forward to maybe a demo or something when the project is further along so we can all have a better sense of it!
